### ISSUE TITLE
get-hints: Problem that compiled PYD files do not compile dependencies modules & PYD file is not copied to dist folder

### ISSUE THREAD

**Issue by SeanTolstoyevski** [Nuitka/NUITKA-Utilities#17]
Hi,

for example
`cythonize --build file.py`
I import the file I compiled with the command "import file" in another file.
Let this file be named **"main.py"** in our example.

`python get-hints.py main.py`

After:

`python nuitka-hints.py main.py`

Compilation is completed in a short time, in 17 seconds.
I cannot find file.cpxx-x.pyd when I look in the dist folder.
I then copy the file I compiled with cythonize to the dist folder.

The dependencies of the PYD file are not compiled, exe shows their error.

Can you add support for resolving the dependencies of PYD files?

Hey, I'm new to this. Maybe I don't know. Please specify them.

## Informations
```
0.6.6rc7
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Executable: D:\d\github\EksiAnalyzer\venv\Scripts\python.exe
OS: Windows
Arch: x86

compilerenv: Developer Command Prompt for VS 2019
```

**Comment by JorjMcKie** [comment]
I am not sure I understand what you are saying:

1. ``get-hints.py`` simply executes your script by the normal Python interpreter. It just logs all imports encountered.
2. ``nuitka-hints.py`` then compiles your script based on the previously created log file.

If the log file contains an entry for your PYD extension, it will be included in the dist folder. There is no difference to other imported modules.

If your PYD however contains other import statements, they cannot be detected, The imported modules will be missing in the dist folder. Such cases must be covered by other means (implicit imports plugin).

**Comment by JorjMcKie** [comment]
I just reconfirmed what I responded in my last post:

1. made two skeleton Python scripts, file.py, test.py, where test.py imports file.py and does nothing else, and file.py prints a message that it has been import.
2. compiled file.py into a PYD extension, ``file.pyd``, removed file.py from that folder
3. executed ``python get-hints.py test.py``, which gave me ``test-37-win32-64.json``.

Ended up with a folder containing

```
25.11.2019  04:15           370.688 file.pyd
25.11.2019  04:16             1.361 test-37-win32-64.json
25.11.2019  04:14                13 test.py
```

4. executed ``python nuitka-hints.py test.py``, which delivered the ``test.dist`` folder containing this:

```
25.11.2019  04:17           702.776 comctl32.dll
25.11.2019  04:17           370.688 file.pyd     <=====
25.11.2019  04:17         3.401.248 libcrypto-1_1.dll
25.11.2019  04:17           688.160 libssl-1_1.dll
25.11.2019  04:17           200.208 pyexpat.pyd
25.11.2019  04:17         3.748.368 python37.dll
25.11.2019  04:17            26.640 select.pyd
25.11.2019  04:17         1.272.848 sqlite3.dll
25.11.2019  04:17         1.705.120 tcl86t.dll
25.11.2019  04:17         7.687.168 test.exe     <=====
25.11.2019  04:17         1.468.064 tk86t.dll
25.11.2019  04:17         1.072.656 unicodedata.pyd
25.11.2019  04:17            89.752 vcruntime140.dll
25.11.2019  04:17            71.696 _asyncio.pyd
25.11.2019  04:17            89.104 _bz2.pyd
25.11.2019  04:17           133.136 _ctypes.pyd
25.11.2019  04:17           268.816 _decimal.pyd
25.11.2019  04:17           209.424 _elementtree.pyd
25.11.2019  04:17            38.928 _hashlib.pyd
25.11.2019  04:17           257.040 _lzma.pyd
25.11.2019  04:17            39.440 _msi.pyd
25.11.2019  04:17            29.200 _multiprocessing.pyd
25.11.2019  04:17            44.560 _overlapped.pyd
25.11.2019  04:17            27.664 _queue.pyd
25.11.2019  04:17            75.792 _socket.pyd
25.11.2019  04:17            86.032 _sqlite3.pyd
25.11.2019  04:17           123.920 _ssl.pyd
25.11.2019  04:17            67.088 _tkinter.pyd
```

and executing test.exe worked as expected.

**Comment by SeanTolstoyevski** [comment]
thanks @JorjMcKie 

In my file

file.py:
```
import requests, bs4....
```
as were the lines.
I didn't know Nuitka couldn't detect them.

I understood your answer.

Thank you so much

**Comment by JorjMcKie** [comment]
> I didn't know Nuitka couldn't detect them.

Nuitka (and get-hints.py) parse the Python **_source code_**. They are (like everything else) not capable of inspecting binary, compiled code (like PYDs).

You know how to heal the situation, don't you?
Look at the Nuitka parameters ``--recurse-to`` etc.
Name all imports in your PYD like this and put those parameters in the compile command like this:

``python nuitka-hints.py --recurse-to=m1 --recurse-to=m2 ... yourscript.py``

**Comment by SeanTolstoyevski** [comment]
> python nuitka-hints.py --recurse-to=m1 --recurse-to=m2 ... yourscript.py

I learned how to do it.

I can close.
