### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape Call cleaning has removed 0 items.

### ISSUE THREAD

**Issue by chwba** [Nuitka/NUITKA-Utilities#21]
python get-hints.py my-script.py gives me this:

`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape Call cleaning has removed 0 items.`

**Comment by deajan** [comment]
What git commit of get-hints.py did you use ?
There was a fix yesterday for UTF-8 stuff, #18. Was this included ?

**Comment by chwba** [comment]
Sadly, no I have just tried again same error

**Comment by deajan** [comment]
Can you post your source script so we can see where the problem is ?

**Comment by chwba** [comment]
Can we send it to you privately?

**Comment by deajan** [comment]
Sure, just send it to contact a netpower.fr



Orsiris de Jong

http://www.netpower.fr

Tél: 06 75 40 48 41





-----Message initial-----
De: chwba <notifications@github.com>
Envoyé: mercredi 8 janvier 2020 13:03
À: Nuitka/NUITKA-Utilities <NUITKA-Utilities@noreply.github.com>
Cc: Orsiris de Jong <ozy@netpower.fr>; Comment <comment@noreply.github.com>
Sujet: Re: [Nuitka/NUITKA-Utilities] SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape Call cleaning has removed 0 items. (#21)

Can we send it to you privately?

**Comment by chwba** [comment]
Here: ozy@netpower.fr ?

**Comment by deajan** [comment]
Yes... Now please remove my mail address from your post, don't want it to be scrapped.

**Comment by chwba** [comment]
Done, thanks

**Comment by deajan** [comment]
I'll have a test this evening.

**Comment by inxp** [comment]
Replacing line 484
 `scriptname = "&scriptname"`
 with 
`scriptname = r"&scriptname"`
 solves it.

**Comment by chwba** [comment]
Very small changes with very big results :dagger:

**Comment by deajan** [comment]
@inxp mind to make a PR ?

**Comment by chwba** [comment]
Do you guys have a Slack or alike?

**Comment by deajan** [comment]
@chwba LMGTFY https://nsis.sourceforge.io/Main_Page
