### ISSUE TITLE
After hinted compilation: App is starting but extremely buggy

### ISSUE THREAD

**Issue by chwba** [Nuitka/NUITKA-Utilities#25]
When using the following arguments while compiling with nuitka manually the app works fine without any bugs:

```
nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --enable-plugin=tk-inter --nofollow-import-to=importlib --recurse-not-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse MRT.py
```

If I compile it with hinted compilation, the compile does finish but the app is, well rather not functional. For example when I start one of its features it will simply open another instance of the main app.

**Comment by JorjMcKie** [comment]
Please provide all information as you would in the main repo and I would also need the app's source to reproduce.

**Comment by chwba** [comment]
What do you mean by "all information as I would in the main repo"? I had already sent a part of our source to @deajan

**Comment by chwba** [comment]
@JorjMcKie @deajan ?

**Comment by deajan** [comment]
@chwba Just give access to your repo and what do you try to accomplish.
Just sending sources is sufficient to know why hinted compilation may have an error, but is not sufficient to know what happens with your program.

**Comment by chwba** [comment]
Alright, I will add you

**Comment by deajan** [comment]
Don't send them to me, I was going to look after the UTF issue, but not this one

**Comment by chwba** [comment]
Can you forward it to your colleague then?
