### ISSUE TITLE
Compiling obfuscated (by pyarmor) source

### ISSUE THREAD

**Issue by chwba** [Nuitka/NUITKA-Utilities#26]
In the meantime I have also tried to compile our project after it was obfuscated by pyarmor. The app is fully functional after obfuscation. - After compiling it with nuitka using  the command:

`nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --enable-plugin=tk-inter --nofollow-import-to=importlib --recurse-not-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse MRT.py`

We get 
```
Traceback (most recent call last):
  File "<C:\Users\user\Desktop\mnwd_tool-obf\dist\MRT.dist\MRT.py>", line 3, in <module>
  File "<frozen MRT>", line 17, in <module>
ModuleNotFoundError: No module named 'PySimpleGUI'
```
See also here: https://github.com/dashingsoft/pyarmor/issues/174

**Comment by deajan** [comment]
If you obfuscate your imports with Pyarmor, there's no way for it to find all imports automagically.
Try adding `import PySimpleGUI` abobe your Pyarmor obfuscated script.

**Comment by chwba** [comment]
If i add an import above `from pytransform import pyarmor_runtime` I get

```
Traceback (most recent call last):
  File "<frozen MRT>", line 267, in protect_pytransform
  File "<frozen MRT>", line 225, in check_obfuscated_script
RuntimeError: unexpected obfuscated script

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<MRT.py>", line 4, in <module>
  File "<frozen MRT>", line 272, in <module>
  File "<frozen MRT>", line 269, in protect_pytransform
RuntimeError: Protection Fault: unexpected obfuscated script
```

This is what the Pyarmor dev told me about this:
```
I'm not familiar with nuitka (pyarmor could pack the scripts with backend tool `PyInstaller). If the scripts have been obfuscated, any dependent module or package imported by the script could not be found by build tool (nuitak or PyInstaller). For PyInstaller, PyArmor does some extra work, I think nuitka need to do some extra work either, refer to
```
https://pyarmor.readthedocs.io/en/latest/how-to-do.html#how-to-pack-obfuscated-scripts

**Comment by JorjMcKie** [comment]
I am entering this discussion at a late point in time.
So forgive me asking: what is the added value of obfuscating something which is **truly compiled C code** - as opposed to Python code, remaining decompilable when packed with PyInstaller or else?

If this still seems not obfuscated enough, I think a solution should be searched which can protect normal binaries (originally coming from Python code or not) against decompilation.
The code which may need such protection at all should be located in the binary ``yourscript`` in the ``dist`` folder (if the Python original was called ``yourscript.py``).

**Comment by kayhayen** [comment]
At this time, Nuitka preserves function names, variable names in the constants blob. It will gain a commercial offering, where I will make this go away, and offer no attack vectors eventually, I hope during the year.

**Comment by chwba** [comment]
> At this time, Nuitka preserves function names, variable names in the constants blob. It will gain a commercial offering, where I will make this go away, and offer no attack vectors eventually, I hope during the year.

Exacty, this is the reason why we are obfuscating it additionally using pyarmor. Check this article:
http://bitboost.com/python-obfuscator/articles_and_resources/does_nuitka_remove_names_of_variables_functions_classes_etc/

**Comment by chwba** [comment]
Im guessing to make  pyarmor -> nuitka work automatically some additional work must be done by nuitka as per here https://github.com/dashingsoft/pyarmor/issues/174 - With additional compilation commands I was now able to get it working manually, what I had to do is the following:

1. Manually obfuscate the main script with the arguments `pyarmor obfuscate --no-cross-protection --restrict 0 foo.py`
2. Manually compile every other script with `pyarmor obfuscate --no-runtime --restrict 0  --no-cross-protection --exact bar.py`
3. Recreate the folder structure of the application and place the "pytransform" folder in every folder of the recreated structure
4. Edit every pyarmor obfuscated script and add all imports above.
5. Compile with nuitka `nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --enable-plugin=tk-inter --nofollow-import-to=importlib --recurse-not-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse MRT.py`
6. Copy the "pytransform" folder in MRT.dist

**Comment by kayhayen** [comment]
I for my part am not interested in `pyarmor` at all. Doing it in Nuitka will be straight forward. It will just keep the proper names, generate C code, and watch out what data it attaches. Leaving out doc strings and stuff is already supported. And using function and class names with arbitrary mappings, while leaving out all details in the code objects, will be something to add. Also tracebacks should not be given.

I just suspect, it's go to be so much easier for Nuitka to do these things. One day of course I will try and look at pyarmor to steal potentially good ideas.

But as I said, zero interest from my side right now. If somebody else feels like doing this, go ahead.

Yours,
Kay

**Comment by kayhayen** [comment]
One cool idea, don't know if it makes sense, but trace backs encryped against a public key would be sweet, that way you get proper tracebacks using the private key. Ah.. it's going to be a funny puzzle game too.

**Comment by deajan** [comment]
> One cool idea, don't know if it makes sense, but trace backs encryped against a public key would be sweet, that way you get proper tracebacks using the private key. Ah.. it's going to be a funny puzzle game too.

OMG !!! That's a killer feature for a "protected" distributable. I freaking love that idea.

As for PyArmor, it just encodes all source code and uses an external dll to unfold it, meaning Nuitka is unable to perform any sort of optimization at all.
So indeed, both projects are incomatible IMHO.

**Comment by chwba** [comment]
Yeah, makes perfect sense to me. - For now we have to  use it because we really don't want, that all the function and variable names will still be visible. - Hope you guys will implement all that soon

**Comment by kayhayen** [comment]
I was going to start with protecting the data with obfuscation first. Like the AES key, you don't want to be in your binary in a clear text portion, that seems more relevant.

@deajan Using a salted value for a hashing of filenames, function names, variable names will probably do, they just got to become unique. Mix in some base64 when doing the output into it, so we can use binary values. I will be on the drawing board soon.

For now, Windows Services and Python 3.8 final touch ups are higher on my list, but I expect to start on this next month.

**Comment by FeelsBadMan1** [comment]
> pyarmor obfuscate --no-cross-protection --restrict 0 main.py

I used nuitka alone then i uploaded it to virustotal and no engine detected it as malicious. I thought nuitka will obfuscate the compiled versions and send the script to 1 - 3 customers until i noticed, that it only compile to c. the dev of nuitka told me to buy commercial because this will obfuscate the script but it cost 250€ what is too much i think. i bought pyarmor earlier but compiling using pyarmor is not really secure as of virtustotal detect malware in the same script even tho no malware is included. It seems like the issue is on pyinstaller so that is why im now trying to use pyarmor & nuitka however the command you sent isnt great in obfuscating i think. im not aware what --no-cross-protection and  --restrict 0 really do also there is no --advanced 2 option on pyarmor as this only exist on pyinstaller. I think the most secure option to use is, copy the mainscript and save it to another name. then replace varnames and so on with something random. i use https://passwordsgenerator.net for random strings. you also can make functions to random names. one example would be following:
```
EZ77spShtMyPZSxT = range
BY47qxe9mPhuaZT7 = 500
kWAg3B8uA2q4w6eC = print
5vtFRCxeVMV5p9Wq = "hello world"

for BY47qxe9mPhuaZT7 in EZ77spShtMyPZSxT:
   kWAg3B8uA2q4w6eC(5vtFRCxeVMV5p9Wq)
```
You also can use bs64 to encode the scrings in the vars and additional you have the option to still use pyarmor and nuitka after editing your code. i think if someone try to obfuscate it he would need to uncompile the .exe then get c code with wired vars that he might not understand. then if he try to convert it back to .py he only will get this mess of vars. dong this will take lot of time and if you oush a updated version before someone is able to reverse your script i dont think he will try it for long.
