### ISSUE TITLE
hinted compilation + onefile-maker-windows.py issues

### ISSUE THREAD

**Issue by eha-ousha** [Nuitka/NUITKA-Utilities#30]
I apply hinted compilation (exe works as expected) and onefile-maker-windows.py. The onefile exe did not produce the desired output. I unpacked this onefile exe and executed the unpacked exe in the unpacked directory.

The first issue was in onefile-maker-windows.py in reduce_nuitka_dist, which removed _decimal.pyd, which crashed my program. This could be resolved by keeping _decimal.pyd.

Now the unpacked exe works as expected, the onefile exe still gives no output. I operate my program with arguments via console input (python do_it.py some args). This works with the unpacked exe (do_it.exe some args), but not with the packed one. Do these arguments have to be passed differently?

**Comment by JorjMcKie** [comment]
Sorry for the delayed reaction - I have been on a longer trip. I will start lookinbg into this now.

**Comment by aiba7339** [comment]
I came across the same situation.
My program additionally needed _multiprocessing.pyd file and I commented out the below lists' contents in onefile-maker-windows.py.

- NUITKA_EXCLUDE_FILES
- NUITKA_EXCLUDE_DIRS

I remade .exe and ran it, and it was executed without no problems.
I think these files are needed to execute the program.
What do you think about it?

**Comment by JorjMcKie** [comment]
I have changed the script according to both of your inputs. The files are needed just too often, and the space savings are minimal in relation.

What I will do instead, is modifying hinted compilation such that it can detect whether or not sqlite3 is being used and remove its components respectively.
