### ISSUE TITLE
Using multiprocessing modules may fail with current log file generation strategy

### ISSUE THREAD

**Issue by deajan** [Nuitka/NUITKA-Utilities#36]
Hello,

Using the current print strategy to write log files, we may have a race condition with get-hints on programs that use multiprocessing.

We should write to a temp log file identified by it's pid then assemble those, in ordre to avoid race conditions.

The following shows a result line being printed, overwritten by a call line on the same line.
```
1;CALL;multiprocessing.managers;[]
1;RESULT;multiprocessing;$PYTHONPATH\multiprocessing\__init__.py
1;CALL;multiprocessing.pool;[]
1;RESULT;multiprocessing;$PYTHONPATH\multiprocessing\_1;CALL;windows_tools.wmi_queries;[]
1;RESULT;windows_tools;$PYTHONPATH\windows_tools\__init__.py
1;CALL;multiprocessing.managers;[]
2;CALL;sys;None
2;RESULT;sys;built-in
```

**Comment by JorjMcKie** [comment]
I originally built a feature into the hinting logic, which caused the creation of a separate logfile per process.
The get-hints.py script concatenates them all before producing the final JSON file.
Someone apparently has removed this capability in the meantime 🙄

**Comment by deajan** [comment]
Guess we'll never know who was the evil mastermind behind this :)
I'll that fixed shortly.

Btw, I'll replace the print to stdout logic with file logic, since some of my programs reconfigure stdout on the fly, that would prevent having anything else than UTF-8 output.
