### ISSUE TITLE
[Request] WxPython support?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Nuitka/NUITKA-Utilities#4]
I tried compiling a WxPython based script but it failed with these errors:

> Now executing Nuitka. Please be patient and let it finish!
python -m nuitka --standalone --python-flag=nosite --remove-output --output-dir="C:\Python\PycharmProjects\GooeyGUI\Wx" "C:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.py"
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Python\Anaconda3\lib\site-packages\wx\lib\eventwatcher.py:401' may require use of '--recurse-directory'.
cl /FoC:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build\module.wx.core.obj /c "C:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build\module.wx.core.cpp" /TP /nologo /EHsc /J /Gd /F8388608 /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=1 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=170 /D_NUITKA_MODULE_COUNT=501 /D_NUITKA_EXE /IC:\Python\Anaconda3\include /IC:\Python\Anaconda3\PC /IC:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build /IC:\Python\Anaconda3\lib\site-packages\nuitka\build\include /IC:\Python\Anaconda3\lib\site-packages\nuitka\build\static_src
C:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build\module.wx.core.cpp(51829): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': undeclared identifier
C:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build\module.wx.core.cpp(51966): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': undeclared identifierscons: *** [C:\Python\PycharmProjects\GooeyGUI\Wx\Wx_Demo_Desktop_Widget_Timer.build\module.wx.core.obj] Error 2
Nuitka compile failed!
Check its output!

Seeing how you're a WxPython fan I have to think it's planned.

**Comment by JorjMcKie** [comment]
Oooey Gooey was a wurm, a mighty wurm was he. He sat upon the railway track - the train he did not see ... oooey gooey!!

That's an ugly one! Looks like a Nuitka problem though. Pls let me have your script for trying it out myself ...

**Comment by JorjMcKie** [comment]
I have successfully compiled lots of wxPython scripts so far. So please send me your failing script to trace down the problem.

**Comment by MikeTheWatchGuy** [comment]
I’m pretty sure it was this one.

Congrats on the progress!!!!!


@mike<mailto:mike_barnett@hotmail.com>

**Comment by JorjMcKie** [comment]
unfortunately the script `Wx_Demo_Desktop_Widget_Timer.py` was not attached, nor can I find it anywhere. Just to do **something** I compiled `PySimpleGUIWx.py` itself - and it worked!
So I wonder what may go wrong in a script using it.
Any guesses - maybe concerning PixelDataBase (which caused the C compiler error)?

**Comment by JorjMcKie** [comment]
@MikeTheWatchGuy - I think this can be closed, right?
