### ISSUE TITLE
TypeError: getSharedLibrarySuffix() missing 1 required positional argument: 'preferred'

### ISSUE THREAD

**Issue by italorecife** [Nuitka/NUITKA-Utilities#43]
`>python get-hints.py teste.py`

```
Traceback (most recent call last):
  File "get-hints.py", line 555, in <module>
    myexit(lname, jname, False)  # transform logfile to JSON file
  File "get-hints.py", line 333, in myexit
    call_analyzer(ifile, text, import_calls, import_files, trace_logic)
  File "get-hints.py", line 196, in call_analyzer
    call_analyzer(f, text, import_calls, import_files, trace_logic)
  File "get-hints.py", line 196, in call_analyzer
    call_analyzer(f, text, import_calls, import_files, trace_logic)
  File "get-hints.py", line 240, in call_analyzer
    hasFilenameExtension(res_file, getSharedLibrarySuffix())  # a shared module!
TypeError: getSharedLibrarySuffix() missing 1 required positional argument: 'preferred'
```

**Comment by kayhayen** [comment]
That's a change that is only in develop version of Nuitka, use stable.

However, I believe the code should not check for "the" suffix, but for all supported suffixes, Nuitka was changed to use the more platform specific one, and now a flag is needed to tell. Checking for all suffixes would be more robust though. I will add a function and use that, but it's breaking for the hinted compilation, so it won't happen before next release.

**Comment by adruino-io** [comment]
As a temporary workaround change the line of get-hints.py
`from nuitka.utils.Utils import getSharedLibrarySuffix`
to
`from nuitka.utils.Importing import getSharedLibrarySuffixes`

**Comment by kayhayen** [comment]
This is now working
